version: '3'
services:
  phaser3_vite:
    build: .
    container_name: phaser3-vite
    ports:
      - '9021:9021'
    volumes:
      - .:/home/node/app:rw
    restart: 'no'
    command: sh
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
